"""Add icons table for icon management

Revision ID: 59042b38c022
Revises: 79697777cf1e
Create Date: 2025-08-16 10:07:52.834811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59042b38c022'
down_revision = '79697777cf1e'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('icons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('svg_content', sa.Text(), nullable=True),
    sa.Column('svg_viewbox', sa.String(length=50), nullable=True),
    sa.Column('svg_fill_color', sa.String(length=7), nullable=True),
    sa.Column('svg_stroke_color', sa.String(length=7), nullable=True),
    sa.Column('lucide_name', sa.String(length=50), nullable=True),
    sa.Column('material_name', sa.String(length=50), nullable=True),
    sa.Column('fontawesome_name', sa.String(length=50), nullable=True),
    sa.Column('lvgl_symbol', sa.String(length=50), nullable=True),
    sa.Column('unicode_char', sa.String(length=10), nullable=True),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('fallback_icon_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fallback_icon_id'], ['icons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_icons_active', 'icons', ['is_active'], unique=False)
    op.create_index('idx_icons_category', 'icons', ['category'], unique=False)
    op.create_index('idx_icons_name', 'icons', ['name'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_icons_name', table_name='icons')
    op.drop_index('idx_icons_category', table_name='icons')
    op.drop_index('idx_icons_active', table_name='icons')
    op.drop_table('icons')
    # ### end Alembic commands ###
