"""Add allow_in_macro field to relay_channels

Revision ID: 79697777cf1e
Revises: 1a1a631ee7ec
Create Date: 2025-08-08 16:00:32.803379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79697777cf1e'
down_revision = '1a1a631ee7ec'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Adicionar campo allow_in_macro à tabela relay_channels
    with op.batch_alter_table('relay_channels') as batch_op:
        batch_op.add_column(sa.Column('allow_in_macro', sa.Boolean(), nullable=True, server_default='1'))
    
    # Atualizar valores existentes para True (permitir por padrão)
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE relay_channels SET allow_in_macro = 1 WHERE allow_in_macro IS NULL"))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remover campo allow_in_macro da tabela relay_channels
    with op.batch_alter_table('relay_channels') as batch_op:
        batch_op.drop_column('allow_in_macro')
    # ### end Alembic commands ###
